### PR TITLE
Cleanup and update

### PR DESCRIPTION
**Pull request by nebeker**

### CODE REVIEW

**Comment by LeeDroid-** [comment]
Cheers buddy!!

**Comment by nebeker** [comment]
Hey, no problem. Life got in the way for a while, but I managed to pick up
the slack on this.

**Comment by LeeDroid-** [comment]
I know the feeling, slowed down somewhat my self! :-/

Actually feel like the app is due a rebuild, it's become a right beast

**Comment by nebeker** [comment]
Looking at all the features it has, I imagine it so.
Are there any interesting new thing in Pie that might be helpful?

**Comment by LeeDroid-** [comment]
That's my next challenge! ;)

I do need to try and make things easier, it's become a little too
complicated

**Comment by nebeker** [comment]
Right. If you're strings are any indication of the architecture, it looks
like there's some duplication of efforts in similar functionality from
different modes of access. Is that right?
An overall refresh would be a good opportunity to consolidate things.

**Pull request merged**
