### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by FatihFIRINCI**

### CODE REVIEW

**Comment by FatihFIRINCI** [comment]
@LeeDroid- Please merge it. Thanks

**Comment by FatihFIRINCI** [comment]
So, I have no right to show my name. Thanks

**Comment by LeeDroid-** [comment]
Huh?

I was correcting my self because auto correct changed your name when I said
thanks.

**Comment by FatihFIRINCI** [comment]
No, I wrote the name to appear in the application. You did not merge. Otherwise faith is a better name :)

**Comment by LeeDroid-** [comment]
Ah ok 😁

I have not updated the app recently, I will soon though, been quite busy

Thanks

Lee

**Pull request closed without merging**
